- project:
    templates:
      - openstack-cover-jobs-neutron
      - release-notes-jobs-python3
      - build-openstack-docs-pti
      - check-requirements
      - openstack-python3-jobs-neutron
    check:
      jobs:
        - neutron-tempest-plugin-tap-as-a-service
        - neutron-tempest-plugin-tap-as-a-service-ovn
    gate:
      jobs:
        - neutron-tempest-plugin-tap-as-a-service
        - neutron-tempest-plugin-tap-as-a-service-ovn
    periodic-weekly:
      jobs:
        - openstack-tox-py310
        - openstack-tox-py313
        - openstack-tox-py313-with-oslo-master
        - neutron-tempest-plugin-tap-as-a-service
