- project:
    templates:
      - openstack-cover-jobs-neutron
      - build-openstack-docs-pti
      - check-requirements
      - openstack-python3-wallaby-jobs-neutron
    check:
      jobs:
        - neutron-tempest-plugin-tap-as-a-service
    gate:
      jobs:
        - neutron-tempest-plugin-tap-as-a-service
